services:
  # 1. Qaybta Backend-ka (Node.js API)
  - type: web
    name: doha-school-backend
    env: node
    rootDir: doha-school/backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  # 2. Qaybta Frontend-ka (React Static Site)
  - type: web # Kani waa sax (Render waxay adeegsanaysaa 'web')
    env: static # Kan ayaa sheegaya inuu yahay Static Site (React)
    name: doha-school-frontend
    rootDir: doha-school/frontend
    buildCommand: npm install && npm run build
    publishPath: dist
